### ISSUE TITLE
takser的方式是不是需要设置12个月的任务，因为每个月打卡的时间不一样

### ISSUE THREAD

**Issue by ZionNuption** [georgehuan1994/DingDing-Automatic-Clock-in#25]

**Comment by georgehuan1994** [comment]
也不是不行... 我自己是2个月的任务，轮换着用

**Comment by amaztony** [comment]
我是弄了一个判断是否为工作日的任务，是工作日则发出打卡通知，否则不发；其余情况配合手动打卡和定时打卡的暂停恢复来查缺补漏。

**Comment by wekingchen** [comment]
> 我是弄了一个判断是否为工作日的任务，是工作日则发出打卡通知，否则不发；其余情况配合手动打卡和定时打卡的暂停恢复来查缺补漏。

请问如何判断是否为工作日呢？能分享一下吗，谢谢

**Comment by TTTTTAILOR** [comment]
我已收到您的邮件，我会在稍后给您回复~

**Comment by TTTTTAILOR** [comment]
哥，小米手机闹钟/日历自带这个判断呀。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月10日(星期五) 下午4:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [georgehuan1994/DingDing-Automatic-Clock-in] takser的方式是不是需要设置12个月的任务，因为每个月打卡的时间不一样 (#25)





  
我是弄了一个判断是否为工作日的任务，是工作日则发出打卡通知，否则不发；其余情况配合手动打卡和定时打卡的暂停恢复来查缺补漏。
  
请问如何判断是否为工作日呢？能分享一下吗，谢谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wekingchen** [comment]
哦，我不是小米手机所以不知道

**Comment by amaztony** [comment]
> > 我是弄了一个判断是否为工作日的任务，是工作日则发出打卡通知，否则不发；其余情况配合手动打卡和定时打卡的暂停恢复来查缺补漏。
> 
> 请问如何判断是否为工作日呢？能分享一下吗，谢谢

就在tasker里加一个任务，每天从[tool.bitefu.net](http://tool.bitefu.net/jiari/)获取今天是不是工作日，是则打卡

**Comment by wekingchen** [comment]
> 

能分享下配置脚本吗？

**Comment by wekingchen** [comment]
> > > 我是弄了一个判断是否为工作日的任务，是工作日则发出打卡通知，否则不发；其余情况配合手动打卡和定时打卡的暂停恢复来查缺补漏。
> > 
> > 
> > 请问如何判断是否为工作日呢？能分享一下吗，谢谢
> 
> 就在tasker里加一个任务，每天从[tool.bitefu.net](http://tool.bitefu.net/jiari/)获取今天是不是工作日，是则打卡

大哥请问能分享下配置脚本吗？

**Comment by YorkOrz** [comment]
我是直接在钉钉打卡页面判断是否有“今日休息”这四个字，有的话今天就不打卡，但是这个需要你们公司人事把需要上班的日期全部排好
